26 call assets with common band names
SpatialDays/stac-generator pull request #29
Opened 2023-06-27 15:30 UTC by ivica3730k

added get_asset_common_name_from_filename function which regex-maps the filename to a common band name.

actual logic of how the mapping is done is implemented in the parser.

Also added a bit of safety logic around reading environment variables

2023-06-27 15:31 UTC, ivica3730k commented
If you have access, see https://github.com/SpatialDays/stac-proprietary-parsers/pull/2

2023-06-27 15:33 UTC, ivica3730k commented
@james-hinton please run tests as I wasnt able to get them up and running

2023-06-28 08:41 UTC, ivica3730k commented
Do we need to do it right now for maxar standard parser too, or can we work on that later?

2023-06-28 09:48 UTC, james-hinton requested changes

2023-06-28 09:48 UTC, james-hinton commented on app/core/redis.py
> +        # not catching this makes it eaiser to debug, as this exception is raised any of the functions and in the try
but now the whole worker will fail

2023-06-28 09:48 UTC, james-hinton commented on app/stac/services/stac_item_creator.py
> +            asset_key = parser.get_asset_common_name_from_filename(return_asset_name(filepath))
Why are we putting this outside of the os parser? This will fail for the example parser and is now not generic.

2023-06-28 10:53 UTC, merged